apiVersion: v1
kind: Secret
metadata:
    name: config-secret
type: Opaque
data:
    mysql-root-username: cm9vdA==
    mysql-password: Tm90ZWJvb2sxMjMh
    mysql-root-password: Tm90ZWJvb2sxMjMh
    mysql-db-name: ZGVtb19kYg==