apiVersion: v1
kind: Service
metadata:
  name: java-service
  namespace: my-namespace
spec:
  selector:
    app: java
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090