apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: my-namespace
  labels:
    app: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - name: mysqldb
        image: mysql:8.0.29
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: mysql-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: config-secret
              key: mysql-db-name